// <auto-generated />
namespace Sistema_Gestion_MEP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IdentitySetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentitySetup));
        
        string IMigrationMetadata.Id
        {
            get { return "202510161922040_IdentitySetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
